preset: laravel

enabled:
  - alpha_ordered_imports
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - length_ordered_imports
  - not_operator_with_successor_space
  - unused_use

finder:
  not-name:
    - index.php
    - server.php
    - _ide_helper*.php
