language: php

php:
  - 7.3

notifications:
  email: false

install:
  - cp .env.local .env
  - touch database/database.sqlite
  - touch database/database-testing.sqlite
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

script:
  - phpunit -v
